// Metrics Encyclopedia data — feeds the interactive dashboard.
// Schema:
//   METRICS[family] = { title, summary, metrics: [...], questions: [...] }
//   metric = { name, what, when, notWhen?, range, direction: "up"|"down", task?, scenario, code?, pitfall? }
//   question = { q, a, followups?: [{q, a}] }

const METRICS = {

classification: {
  title: "Classification",
  summary: "28 metrics — different lenses on a confusion matrix.",
  metrics: [
    { name: "Accuracy", what: "(TP+TN) / total — overall correct fraction.", when: "Roughly balanced classes; sanity check.", notWhen: "Imbalanced data (predicting the majority class scores 99%).", range: "[0, 1]", direction: "up", task: "binary/multiclass/multilabel",
      scenario: "Balanced ImageNet subset top-line KPI.",
      code: "from torchmetrics.classification import Accuracy\nacc = Accuracy(task='multiclass', num_classes=10)",
      pitfall: "Multilabel 'accuracy' has two definitions — per-label and subset. Pick explicitly." },
    { name: "Precision", what: "TP / (TP+FP) — of positive predictions, what fraction are right?", when: "Acting on a positive prediction is expensive.", notWhen: "Missing a positive is the more expensive error.", range: "[0, 1]", direction: "up", task: "all",
      scenario: "Spam-filter promotion gated on precision ≥ 99%.",
      code: "Precision(task='binary', threshold=0.5)",
      pitfall: "Predicting positive once correctly = 1.0. Co-report recall." },
    { name: "Recall (Sensitivity)", what: "TP / (TP+FN) — of real positives, how many caught?", when: "Missing a positive is expensive (medical, fraud).", range: "[0, 1]", direction: "up", task: "all",
      scenario: "Cancer screening: recall ≥ 95% under regulator." },
    { name: "Specificity", what: "TN / (TN+FP) — of real negatives, how many correctly left alone?", when: "Cost on negatives matters (over-treating healthy patients).", range: "[0, 1]", direction: "up", task: "binary",
      scenario: "COVID rapid antigen test: specificity floor ≥ 99%.",
      pitfall: "For multilabel, TN dominates → trivially ~1.0." },
    { name: "F1 / FBeta", what: "Harmonic mean of P and R; β trades off (β>1 favours recall).", when: "Imbalanced classes, single-number P-vs-R behaviour.", range: "[0, 1]", direction: "up", task: "all",
      scenario: "Search team uses F2 (recall twice as important).",
      pitfall: "macro vs weighted vs micro — most common interview trap." },
    { name: "MCC (Matthews CorrCoef)", what: "Pearson correlation of binary indicator vectors; uses all 4 cells.", when: "Heavy class imbalance, single-number selection.", range: "[-1, 1]", direction: "up", task: "binary/multiclass",
      scenario: "Fraud team uses MCC to gate model promotion." },
    { name: "AUROC", what: "Pr(score(positive) > score(negative)). Threshold-free ranking quality.", when: "Compare models without committing to a threshold.", notWhen: "Severe imbalance — use AUPRC.", range: "[0, 1]", direction: "up", task: "all",
      scenario: "Two ad-CTR models compared offline at the leaderboard.",
      pitfall: "Ignores calibration." },
    { name: "AveragePrecision (AUPRC)", what: "Area under precision-recall curve.", when: "Imbalanced binary or multilabel; rare positives.", range: "[0, 1]", direction: "up", task: "all",
      scenario: "Fraud detection at 0.05% positive: AUPRC of 0.30 vs random 0.0005 = 600× lift." },
    { name: "CalibrationError (ECE)", what: "Bin-weighted gap between confidence and accuracy.", when: "Downstream uses probabilities (cost decisions, ensembling).", range: "[0, 1]", direction: "down", task: "binary/multiclass",
      scenario: "Loan-default model calibration: AUROC 0.86 but ECE 0.18 → mispriced loans." },
    { name: "ConfusionMatrix", what: "Full per-class confusion table.", when: "Diagnose what's confused with what.", range: "counts", direction: "up", task: "multiclass/multilabel",
      scenario: "Speech-command model: 'left' → 'right' jumped from 0.5% to 3% — found via confusion." },
    { name: "JaccardIndex (IoU on labels)", what: "|y ∩ ŷ| / |y ∪ ŷ| at the label level.", when: "Multilabel where set overlap is the natural KPI.", range: "[0, 1]", direction: "up", task: "multilabel",
      scenario: "Multilabel medical-imaging tagger." },
    { name: "ExactMatch", what: "Subset accuracy — every label must match.", when: "Strict multilabel contracts.", range: "[0, 1]", direction: "up", task: "multilabel",
      scenario: "Regulatory document tagging: one tag wrong = manual review." },
    { name: "HammingDistance", what: "Fraction of individual labels wrong.", when: "Loose multilabel — partial credit.", range: "[0, 1]", direction: "down", task: "multilabel",
      scenario: "Image tagger: missing 1 of 3 hurts 1/3 as much as missing all." },
    { name: "CohenKappa", what: "Agreement corrected for chance.", when: "Inter-rater / model-vs-human agreement.", range: "[-1, 1]", direction: "up", task: "binary/multiclass",
      scenario: "Two radiologists + model rate 1k cases — κ for publication." },
    { name: "EER", what: "Threshold where FPR = FNR.", when: "Biometric/verification — vendor-comparable.", range: "[0, 0.5]", direction: "down", task: "binary",
      scenario: "Speaker verification leaderboard." },
    { name: "LogAUROC", what: "AUROC with log-scaled FPR axis.", when: "Top-of-list focus (rare positives).", range: "[0, 1]", direction: "up", task: "binary",
      scenario: "Drug screening: only top 0.1% candidates assayed." },
    { name: "PrecisionAtFixedRecall", what: "Precision when threshold tuned to fix recall.", when: "Deployment with a recall floor.", range: "[0, 1]", direction: "up", task: "binary",
      scenario: "Spam filter: 'precision at recall ≥ 90%' for SLA." },
    { name: "RecallAtFixedPrecision", what: "Recall when threshold tuned to fix precision.", when: "Deployment with a precision floor.", range: "[0, 1]", direction: "up", task: "binary",
      scenario: "Document classifier: precision ≥ 95% required." },
    { name: "SpecificityAtSensitivity", what: "Specificity at fixed sensitivity floor.", when: "Medical/safety with regulator-mandated sensitivity.", range: "[0, 1]", direction: "up", task: "binary",
      scenario: "Cancer screening: SpecAtSens(min_sens=0.95)." },
    { name: "SensitivityAtSpecificity", what: "Sensitivity at fixed specificity floor.", when: "Medical/safety with FPR cap.", range: "[0, 1]", direction: "up", task: "binary",
      scenario: "Diagnostic test with vendor-mandated FPR ceiling." },
    { name: "BinaryFairness", what: "Per-group TPR/FPR/precision and disparate-impact ratios.", when: "Fairness audits.", range: "ratios target 1.0", direction: "up", task: "binary",
      scenario: "Loan approval: FPR(A)/FPR(B) = 1.7 → biased against group B.",
      pitfall: "Pre-commit to a fairness definition (impossibility result)." },
    { name: "MultilabelRankingAveragePrecision", what: "Per-sample AP of predicted ranking restricted to true labels.", when: "Top-k tag prediction.", range: "[0, 1]", direction: "up", task: "multilabel",
      scenario: "Document tag predictor with ranked top-k output." },
    { name: "StatScores", what: "Raw (TP, FP, TN, FN, support) tuple.", when: "Compose multiple metrics on top — efficient.", range: "counts", direction: "up", task: "all",
      scenario: "Multi-metric DDP dashboard logged hourly." },
    { name: "PrecisionRecallCurve", what: "Full (P, R, thresholds) arrays.", when: "Picking a deployment threshold.", range: "[0,1]×[0,1]", direction: "up", task: "binary/multilabel",
      scenario: "Operating-point selection: 50 alerts/day capacity." },
    { name: "ROC", what: "Full (TPR, FPR, thresholds) arrays.", when: "Plotting / threshold-free analysis.", range: "[0,1]×[0,1]", direction: "up", task: "binary/multiclass",
      scenario: "Per-class ROC for multiclass model audit." },
    { name: "HingeLoss", what: "max(0, 1 − y·f(x)) — SVM loss.", when: "Training diagnostic for margin-based models.", range: "[0, ∞)", direction: "down", task: "binary",
      scenario: "Tracking SVM margin during training." },
    { name: "NegativePredictiveValue (NPV)", what: "TN / (TN + FN) — when we say negative, are we right?", when: "Negative prediction triggers an action (release patient, accept transaction).", range: "[0, 1]", direction: "up", task: "binary",
      scenario: "Hospital triage low-acuity bucket — NPV must be high." },
    { name: "GroupFairness (BinaryGroupStatRates)", what: "Per-group TPR/FPR/precision rates.", when: "Demographic parity / equalised odds audits.", range: "[0, 1] per group", direction: "up", task: "binary",
      scenario: "Compliance review of credit model." }
  ],
  questions: [
    { q: "Walk me through accuracy/precision/recall/F1 — when does each fail?",
      a: "Accuracy fails under imbalance. Precision fails alone (predict positive once, P=1). Recall fails alone (predict everything, R=1). F1 hides P-vs-R asymmetry; F2/F0.5 expose. Every scalar misleads under imbalance.",
      followups: [
        { q: "F1 vs MCC vs AUPRC for imbalanced binary?",
          a: "AUPRC for ranking. F1 needs a threshold; pick for operating point. MCC for single-number gating — uses all four cells, isn't fooled by majority predictors." },
        { q: "Macro vs weighted F1?",
          a: "Macro = unweighted mean per class (every class equal). Weighted = sample-weighted (every sample equal). On 99/1 data they differ massively." }
      ] },
    { q: "Why is AUROC bad for fraud detection?",
      a: "AUROC dominates on easy negatives. At 0.05% base rate, AUROC = 0.99 with garbage top-of-list. AUPRC reflects rare-positive lift correctly.",
      followups: [
        { q: "AUPRC random baseline?",
          a: "Equal to base rate. So AUPRC of 0.30 at 0.05% positive = 600× lift." }
      ] },
    { q: "What is calibration and how do you measure it?",
      a: "Calibrated if Pr(y=1 | model says p) = p. Measure with ECE: bin by confidence, take weighted gap between bin accuracy and bin confidence. n_bins=15 standard.",
      followups: [
        { q: "AUROC great, ECE bad — ship?",
          a: "Depends on downstream consumer. Threshold-only systems: ship. Probability-consuming systems: post-hoc Platt or isotonic calibration first." }
      ] },
    { q: "Top-1 vs top-5 accuracy — why both?",
      a: "Top-5 absorbs irreducible label ambiguity (dog breeds). Top-1 is what argmax-deployed systems care about. Together: did you get exact label vs right neighbourhood." },
    { q: "What would you log for binary classification?",
      a: "Accuracy + Precision + Recall + F1 + AUROC + AUPRC + ECE + SpecificityAtSensitivity(0.95) + ConfusionMatrix. As a MetricCollection so DDP and compute_groups dedupe state." }
  ]
},

regression: {
  title: "Regression",
  summary: "22 metrics — different loss surfaces on the residual.",
  metrics: [
    { name: "MeanAbsoluteError (MAE)", what: "Average |y − ŷ| in target units.", when: "Roughly equal error costs; user-facing units.", range: "[0, ∞)", direction: "down",
      scenario: "ETA prediction for ride-share." },
    { name: "MeanSquaredError (MSE)", what: "Average (y − ŷ)².", when: "Training loss — smooth gradient.", range: "[0, ∞)", direction: "down",
      scenario: "Weather temperature loss." },
    { name: "RootMeanSquaredError (RMSE)", what: "sqrt(MSE) — same units as target.", when: "Outlier-sensitive reporting.", range: "[0, ∞)", direction: "down",
      scenario: "Weather temperature reporting standard." },
    { name: "NRMSE", what: "RMSE / norm (mean / iqr / range).", when: "Cross-product / cross-scale comparison.", range: "[0, ∞)", direction: "down",
      scenario: "Cross-store demand forecast leaderboard." },
    { name: "MAPE", what: "Average |y − ŷ| / |y|.", when: "Forecasting in % terms.", notWhen: "Targets near zero, asymmetric cost.", range: "[0, ∞)", direction: "down",
      scenario: "Quarterly revenue forecast.",
      pitfall: "Asymmetric — rewards under-forecasting." },
    { name: "sMAPE (symmetric)", what: "2|y − ŷ| / (|y| + |ŷ|).", when: "Symmetric % error; M3/M4 forecasting.", range: "[0, 2]", direction: "down",
      scenario: "Forecast competition standard." },
    { name: "wMAPE (weighted)", what: "Σ|y − ŷ| / Σ|y| — pooled.", when: "Volume-weighted % error.", range: "[0, ∞)", direction: "down",
      scenario: "Multi-SKU demand: high-volume SKU matters more." },
    { name: "R²", what: "1 − SS_res / SS_tot.", when: "Relative quality across datasets.", range: "(-∞, 1]", direction: "up",
      scenario: "House-price model: R² = 0.85 across cities.",
      pitfall: "Negative R² = worse than mean — don't clip." },
    { name: "ExplainedVariance", what: "1 − Var(y − ŷ) / Var(y).", when: "Bias is calibrated separately.", range: "(-∞, 1]", direction: "up",
      scenario: "Bias-corrected weather forecast." },
    { name: "Pearson Correlation", what: "Linear correlation.", when: "Ranking strength.", range: "[-1, 1]", direction: "up",
      scenario: "Sanity-check: high ρ + bad RMSE = calibration issue." },
    { name: "Spearman Correlation", what: "Pearson on ranks; outlier-robust.", when: "Monotonic relationships.", range: "[-1, 1]", direction: "up",
      scenario: "IR scoring quality." },
    { name: "Kendall Tau", what: "Pairwise concordance.", when: "Strict pairwise ranking.", range: "[-1, 1]", direction: "up",
      scenario: "Top-10 list rank quality." },
    { name: "Concordance CC", what: "Lin's CCC — correlation + bias.", when: "Method-comparison studies.", range: "[-1, 1]", direction: "up",
      scenario: "Sensor agreement vs gold standard." },
    { name: "CosineSimilarity", what: "Direction agreement.", when: "Embedding regression.", range: "[-1, 1]", direction: "up",
      scenario: "Sentence-embedding regression." },
    { name: "Tweedie Deviance", what: "Bregman divergence for compound Poisson-Gamma.", when: "Non-negative target with point mass at 0.", range: "[0, ∞)", direction: "down",
      scenario: "Insurance claim severity." },
    { name: "CRPS", what: "Integrated squared error between predicted CDF and indicator of truth.", when: "Probabilistic forecasts (ensemble, quantile).", range: "[0, ∞)", direction: "down",
      scenario: "Wind-power ensemble forecasting." },
    { name: "MinkowskiDistance", what: "(Σ|y − ŷ|^p)^(1/p).", when: "Tunable knob between MAE and RMSE.", range: "[0, ∞)", direction: "down",
      scenario: "Hyperparameter sweep on the metric itself." },
    { name: "LogCoshError", what: "log(cosh(y − ŷ)) — smooth Huber-like.", when: "Robust regression training without δ.", range: "[0, ∞)", direction: "down",
      scenario: "Training loss for outlier-robust regression." },
    { name: "LogMSE", what: "MSE in log-space.", when: "Multi-order-of-magnitude targets.", range: "[0, ∞)", direction: "down",
      scenario: "Demand forecasting across SKUs spanning 1-10000 units." },
    { name: "RelativeSquaredError", what: "Σ(y−ŷ)² / Σ(y−ȳ)².", when: "Complement of R².", range: "[0, ∞)", direction: "down",
      scenario: "Tracking 1-R² when R² is negative." },
    { name: "KL Divergence", what: "Σ p log(p/q).", when: "Drift detection (asymmetric).", range: "[0, ∞)", direction: "down",
      scenario: "Training-vs-prod feature distribution drift." },
    { name: "JS Divergence", what: "Symmetric KL: 0.5·KL(p||M) + 0.5·KL(q||M).", when: "Default drift metric.", range: "[0, log 2]", direction: "down",
      scenario: "Production drift dashboard." }
  ],
  questions: [
    { q: "MAE vs RMSE — when?",
      a: "RMSE squares — outlier-sensitive. MAE linear — robust. Use MAE for equally-costly errors (ETA), RMSE for disproportionate cost (peak load).",
      followups: [
        { q: "RMSE >> MAE — what does it tell you?",
          a: "Heavy-tailed residuals. Outliers or heteroscedasticity. Plot |residual| vs ŷ to distinguish." }
      ] },
    { q: "MAPE has issues — name three.",
      a: "Targets near zero blow up; asymmetric (under-forecast capped at 100%, over unbounded); no negatives. Replacements: sMAPE, wMAPE, MASE.",
      followups: [
        { q: "Business demands MAPE — how to push back?",
          a: "Don't push back on the report; train on quantile loss or Tweedie, evaluate on MAPE." }
      ] },
    { q: "Why is R² sometimes negative?",
      a: "SS_res > SS_tot. Worse than predicting mean. Don't clip — informative." },
    { q: "Pearson is high but RMSE is bad — diagnosis?",
      a: "Pearson is invariant to scale and offset. Calibration issue (slope/offset). Use Concordance CC for agreement." },
    { q: "What's CRPS?",
      a: "Generalises MAE to probabilistic forecasts. Reduces to MAE for Dirac. Strictly proper — minimised when predicted = true distribution." }
  ]
},

retrieval: {
  title: "Retrieval",
  summary: "10 metrics — different rank-position weights.",
  metrics: [
    { name: "NDCG", what: "DCG / IDCG with logarithmic position discount.", when: "Graded relevance, deep ranked lists.", range: "[0, 1]", direction: "up",
      scenario: "E-commerce search leaderboard." },
    { name: "MAP (Mean Average Precision)", what: "Per query, AP = (1/R)Σ P@k · 1[relevant].", when: "Binary relevance, deep retrieval.", range: "[0, 1]", direction: "up",
      scenario: "TREC document retrieval." },
    { name: "MRR", what: "1 / rank_of_first_relevant.", when: "QA / navigational search.", range: "[0, 1]", direction: "up",
      scenario: "Voice assistant: 'find official Apple page' — only first hit matters." },
    { name: "HitRate", what: "1 if any of top-k is relevant else 0.", when: "Recsys carousel; coarse signal.", range: "[0, 1]", direction: "up",
      scenario: "Top-10 recommendation: did user click anything?" },
    { name: "RPrecision", what: "Precision at k=R (number of relevants).", when: "Variable-difficulty queries.", range: "[0, 1]", direction: "up",
      scenario: "TREC with variable R per query." },
    { name: "Precision@k", what: "Per query top-k precision.", when: "Fixed-size result list (search).", range: "[0, 1]", direction: "up",
      scenario: "Top-10 search precision." },
    { name: "Recall@k", what: "Per query top-k recall.", when: "Set-completion / target retrieval.", range: "[0, 1]", direction: "up",
      scenario: "Bug-similar-issue retrieval." },
    { name: "FallOut", what: "FPR over top-k.", when: "Information retrieval pollution analysis.", range: "[0, 1]", direction: "down",
      scenario: "Large-corpus IR research." },
    { name: "RetrievalAUROC", what: "Per-query AUROC averaged.", when: "Per-query ranking quality, variable size.", range: "[0, 1]", direction: "up",
      scenario: "Per-user ad ranker." },
    { name: "PrecisionRecallCurve", what: "Per-query PR curve averaged.", when: "Depth-vs-precision study.", range: "[0,1]×[0,1]", direction: "up",
      scenario: "Pick the elbow for user-facing top-k." }
  ],
  questions: [
    { q: "NDCG vs MAP — when?",
      a: "NDCG for graded relevance (e-commerce). MAP for binary (TREC). Both reward putting relevants high; NDCG's discount is logarithmic; normalised per query.",
      followups: [
        { q: "Why NDCG even for binary?",
          a: "Log discount tracks user attention; per-query normalisation removes scale issues." }
      ] },
    { q: "Most common retrieval bug?",
      a: "Forgetting indexes= argument. Without it, all items pool into one giant ranked list and the metric is meaningless (and misleadingly high)." },
    { q: "1M items — too slow. What do you do?",
      a: "NDCG@k matching user-facing depth + sub-sample negatives (all positives + 100 randoms). Unbiased estimator." },
    { q: "MRR is brutal — why?",
      a: "MRR=0 if first relevant is past top_k. So MRR is only meaningful when (a) top_k matches user-facing, (b) finding the relevant in top-k is the system's job." }
  ]
},

detection: {
  title: "Detection",
  summary: "8 metrics — IoU variants and mAP/PQ.",
  metrics: [
    { name: "IoU (IntersectionOverUnion)", what: "|A ∩ B| / |A ∪ B|.", when: "Per-prediction overlap diagnostic.", range: "[0, 1]", direction: "up",
      scenario: "Per-detection match diagnostic.",
      pitfall: "Non-differentiable at 0 overlap — use GIoU for losses." },
    { name: "GIoU", what: "IoU − wasted enclosing area.", when: "Bbox training loss — smooth gradient.", range: "[-1, 1]", direction: "up",
      scenario: "One-stage detector loss." },
    { name: "DIoU", what: "GIoU + centre-distance penalty.", when: "Faster bbox training convergence.", range: "[-1, 1]", direction: "up",
      scenario: "YOLO-style training." },
    { name: "CIoU", what: "DIoU + aspect-ratio penalty.", when: "Standard YOLO-v4+ training loss.", range: "[-1, 1]", direction: "up",
      scenario: "Modern detector training." },
    { name: "Mean Average Precision (mAP)", what: "Mean over classes of AP from sorted-by-confidence PR curves at IoU thresholds.", when: "Object detection — the standard.", range: "[0, 1]", direction: "up",
      scenario: "COCO benchmark / leaderboard.",
      pitfall: "Wrong box_format (xyxy vs xywh) — silent garbage numbers." },
    { name: "Panoptic Quality (PQ)", what: "SQ × RQ (segmentation × recognition quality).", when: "Panoptic segmentation.", range: "[0, 1]", direction: "up",
      scenario: "Self-driving stack panoptic head." }
  ],
  questions: [
    { q: "Walk through mAP computation.",
      a: "Per class: match preds-to-truth in confidence order at IoU threshold; PR curve from TPs/FPs/FNs; AP = area. mAP = mean over classes (and IoU thresholds for COCO).",
      followups: [
        { q: "Why average over IoU thresholds?",
          a: "VOC mAP@0.5 rewards loose boxes. COCO [.5:.95] forces tight boxes — better matches deployment in self-driving etc." }
      ] },
    { q: "IoU vs GIoU/DIoU/CIoU?",
      a: "IoU for evaluation (zero overlap = 0). GIoU smooth (negative for non-overlap). DIoU adds centre-distance. CIoU adds aspect-ratio. CIoU is standard YOLO+." },
    { q: "mAP regressed from 0.42 to 0.40 — debug?",
      a: "Drill down: map_50 vs map_75 (loose vs tight); per-area-bucket; per-class AP. A small-object-class collapse looks identical at top-line to a tight-IoU regression — different fixes." },
    { q: "Most common detection bug?",
      a: "Wrong box_format. Default xyxy; YOLO emits xywh. IoU computes wrong overlap silently." }
  ]
},

segmentation: {
  title: "Segmentation",
  summary: "4 metrics — pixel-wise overlap.",
  metrics: [
    { name: "MeanIoU", what: "Per-class IoU averaged.", when: "Semantic segmentation.", range: "[0, 1]", direction: "up",
      scenario: "Cityscapes / ADE20K leaderboard." },
    { name: "Dice", what: "2·TP / (2·TP + FP + FN). Equivalent to F1 on pixels.", when: "Medical imaging.", range: "[0, 1]", direction: "up",
      scenario: "Tumor segmentation BraTS challenge." },
    { name: "Generalized Dice", what: "Dice with per-class weight 1/volume².", when: "Class imbalance (background dominates).", range: "[0, 1]", direction: "up",
      scenario: "3D multi-organ segmentation." },
    { name: "Hausdorff Distance", what: "Max of nearest-neighbour distances.", when: "Boundary-critical (radiation therapy).", range: "[0, ∞)", direction: "down",
      scenario: "Radiation oncology contouring.",
      pitfall: "Sensitive to outliers — use Hausdorff95." }
  ],
  questions: [
    { q: "Dice vs IoU — same info?",
      a: "Yes, monotone equivalent. Dice = 2·IoU/(1+IoU). One is enough; medical imaging picks Dice, general CV picks mIoU." },
    { q: "When does Dice/IoU lie?",
      a: "Boundary errors. Pixel-perfect bulk + 50-pixel spurious tail = high IoU but bad surgery. Use Hausdorff95 for boundary precision." },
    { q: "Why Generalized Dice?",
      a: "Multi-class with one dominant class (background 90%): standard Dice mean is dominated by background. Generalized weights by 1/volume² for fairness." }
  ]
},

image: {
  title: "Image quality",
  summary: "23 metrics — reference, distribution, no-reference.",
  metrics: [
    { name: "PSNR", what: "10·log10(MAX²/MSE) in dB.", when: "Compression / codec.", range: "[0, ∞)", direction: "up",
      scenario: "JPEG quality reporting.",
      pitfall: "data_range argument — set explicitly." },
    { name: "SSIM", what: "Window-wise luminance × contrast × structure.", when: "Better than PSNR for perception.", range: "[-1, 1]", direction: "up",
      scenario: "Super-resolution leaderboards." },
    { name: "MS-SSIM", what: "Multi-scale SSIM.", when: "Multi-scale structure capture.", range: "[0, 1]", direction: "up",
      scenario: "LIVE / TID2013 IQA datasets." },
    { name: "LPIPS", what: "Deep-feature distance calibrated to human judgments.", when: "Perceptual fidelity.", range: "[0, ∞)", direction: "down",
      scenario: "GAN super-resolution reporting." },
    { name: "DISTS", what: "Deep texture + structure similarity.", when: "Newer LPIPS variant.", range: "[0, 1]", direction: "down",
      scenario: "IQA where texture matters." },
    { name: "FID", what: "Frechet distance between Gaussian-fit Inception features.", when: "Generative model quality.", range: "[0, ∞)", direction: "down",
      scenario: "GAN/diffusion paper leaderboard.",
      pitfall: "Biased low for small N — use ≥ 50k samples." },
    { name: "KID", what: "MMD with polynomial kernel on Inception features.", when: "Small-N unbiased FID alternative.", range: "[0, ∞)", direction: "down",
      scenario: "Few-sample generative eval." },
    { name: "MIFID", what: "FID with memorisation penalty.", when: "Generative competitions / anti-copying.", range: "[0, ∞)", direction: "down",
      scenario: "Kaggle generative challenges." },
    { name: "InceptionScore", what: "exp(E[KL(p(y|x) || p(y))]).", when: "Legacy GAN reporting.", range: "[1, #classes]", direction: "up",
      scenario: "Pre-2018 GAN papers." },
    { name: "PerceptualPathLength", what: "Avg perceptual distance along latent path.", when: "Latent-space smoothness (StyleGAN).", range: "[0, ∞)", direction: "down",
      scenario: "StyleGAN latent quality." },
    { name: "VIF", what: "Mutual information ratio.", when: "Information-theoretic IQA.", range: "[0, 1]", direction: "up",
      scenario: "IQA challenges." },
    { name: "UQI", what: "Correlation × luminance × contrast.", when: "Predecessor of SSIM.", range: "[-1, 1]", direction: "up",
      scenario: "Legacy IQA pipelines." },
    { name: "SAM (Spectral Angle Mapper)", what: "Per-pixel angle between spectral vectors.", when: "Hyperspectral imaging.", range: "[0, π]", direction: "down",
      scenario: "Hyperspectral material identification." },
    { name: "ERGAS", what: "Relative RMSE across bands × resolution ratio.", when: "Pansharpening fidelity.", range: "[0, ∞)", direction: "down",
      scenario: "Satellite pansharpening evaluation." },
    { name: "RASE", what: "Average relative spectral error.", when: "Multispectral remote sensing.", range: "[0, ∞)", direction: "down",
      scenario: "Pansharpening companion to ERGAS." },
    { name: "SCC", what: "Edge-detected correlation.", when: "Spatial fidelity in pansharpening.", range: "[-1, 1]", direction: "up",
      scenario: "Synthesised panchromatic edge agreement." },
    { name: "RMSE-SW", what: "Sliding-window RMSE.", when: "Local error sensitivity.", range: "[0, ∞)", direction: "down",
      scenario: "Spatially-varying distortion analysis." },
    { name: "TotalVariation", what: "Σ|∇I|.", when: "Smoothness regulariser/diagnostic.", range: "[0, ∞)", direction: "down",
      scenario: "Inverse-problem regularisation." },
    { name: "PSNR-B", what: "PSNR + blocking-artefact penalty.", when: "Block codec evaluation (JPEG, HEVC).", range: "[0, ∞)", direction: "up",
      scenario: "Codec quality where blocking matters." },
    { name: "D_λ (Spectral Distortion Index)", what: "Spectral distortion in pansharpened.", when: "No-reference pansharpening.", range: "[0, 1]", direction: "down",
      scenario: "Field pansharpening QA." },
    { name: "D_S (Spatial Distortion Index)", what: "Spatial distortion in pansharpened.", when: "No-reference pansharpening.", range: "[0, 1]", direction: "down",
      scenario: "Field pansharpening QA." },
    { name: "QNR", what: "Combined D_λ and D_S.", when: "No-reference pansharpening QC.", range: "[0, 1]", direction: "up",
      scenario: "Field deployment pansharpening." },
    { name: "ARNIQA", what: "Self-supervised no-reference quality scorer.", when: "User-uploaded content QA.", range: "score", direction: "up",
      scenario: "Social media upload quality screening." }
  ],
  questions: [
    { q: "Why is FID biased for small N?",
      a: "Empirical covariance underestimates → trace term shrinks → FID estimate too low. 50k samples standard. KID is unbiased for small N.",
      followups: [
        { q: "Only 5000 generated images — what do you report?",
          a: "KID with bootstrap CIs. Or: subsample real to match (symmetric bias). Don't compare FID across different N." }
      ] },
    { q: "PSNR vs SSIM vs LPIPS?",
      a: "PSNR = MSE in dB (engineering). SSIM = window-wise structure (better perception). LPIPS = deep features calibrated to humans (best perception). Report all three for SR." },
    { q: "Generative model FID 12→8 — real win?",
      a: "Check: N consistent, preprocessing identical, multiple seeds. A 4-point drop on top of ±5 std isn't significant. Plus: state truncation level alongside the number." }
  ]
},

text: {
  title: "Text / NLP",
  summary: "16 metrics — n-gram, edit, embedding, LM-based.",
  metrics: [
    { name: "BLEU", what: "n-gram precision with brevity penalty.", when: "Machine translation.", range: "[0, 1]", direction: "up",
      scenario: "WMT leaderboard.",
      pitfall: "Tokenisation-dependent — use SacreBLEU." },
    { name: "SacreBLEU", what: "BLEU with standardised tokeniser.", when: "Cross-paper MT comparison.", range: "[0, 1]", direction: "up",
      scenario: "Modern WMT submission requirement." },
    { name: "ROUGE", what: "n-gram recall + LCS-based F1.", when: "Summarisation.", range: "[0, 1]", direction: "up",
      scenario: "CNN/DailyMail / XSum leaderboards." },
    { name: "chrF", what: "Character n-gram F-score.", when: "Morphologically-rich languages.", range: "[0, 1]", direction: "up",
      scenario: "WMT for Finnish, Turkish, Russian." },
    { name: "EditDistance", what: "Min insert/delete/substitute ops.", when: "Spell correction, OCR.", range: "[0, ∞)", direction: "down",
      scenario: "Keystroke correction analysis." },
    { name: "TER (Translation Edit Rate)", what: "EditDistance / |reference|.", when: "MT post-editing effort estimation.", range: "[0, ∞)", direction: "down",
      scenario: "Predicting human translator workload." },
    { name: "EED (Extended Edit Distance)", what: "Edit distance + character-level + transposition.", when: "Fine-grained MT eval.", range: "[0, ∞)", direction: "down",
      scenario: "MT evaluation alongside chrF." },
    { name: "WER (Word Error Rate)", what: "(S+D+I) / N.", when: "Speech recognition.", range: "[0, ∞)", direction: "down",
      scenario: "ASR system evaluation.",
      pitfall: "Can exceed 100% with hallucination — use MER for bounded." },
    { name: "CER (Character Error Rate)", what: "Char-level WER.", when: "OCR / no-word-boundary languages.", range: "[0, ∞)", direction: "down",
      scenario: "Chinese / Thai ASR; OCR systems." },
    { name: "MER (Match Error Rate)", what: "(S+D+I) / (H+S+D+I) — bounded WER.", when: "Want a [0,1]-bounded ASR metric.", range: "[0, 1]", direction: "down",
      scenario: "Dashboard-friendly ASR metric." },
    { name: "WIL (Word Information Lost)", what: "Information-theoretic ASR error.", when: "Information-loss reporting.", range: "[0, 1]", direction: "down",
      scenario: "Theoretical ASR analysis." },
    { name: "WIP (Word Information Preserved)", what: "1 − WIL.", when: "Higher-better complement of WIL.", range: "[0, 1]", direction: "up",
      scenario: "Analytics dashboard variant." },
    { name: "BERTScore", what: "BERT-embedding cosine F1.", when: "Open-ended generation, paraphrase.", range: "[0, 1]", direction: "up",
      scenario: "Summarisation evaluation beyond ROUGE.",
      pitfall: "Pin backbone; rescale_with_baseline for readability." },
    { name: "InfoLM", what: "Info-theoretic LM-based distance.", when: "Strong-LM-based eval.", range: "[0, 1]", direction: "up",
      scenario: "Text quality alongside BERTScore." },
    { name: "Perplexity", what: "exp(NLL).", when: "LM training tracking.", range: "[1, ∞)", direction: "down",
      scenario: "Pretraining headline.",
      pitfall: "Not comparable across tokenisers — use BPB." },
    { name: "SQuAD F1/EM", what: "Token-overlap F1 + exact match.", when: "Extractive QA.", range: "[0, 1]", direction: "up",
      scenario: "SQuAD-1.1 benchmark." }
  ],
  questions: [
    { q: "BLEU vs SacreBLEU?",
      a: "BLEU is tokeniser-dependent. SacreBLEU pins it. WMT mandates SacreBLEU now.",
      followups: [
        { q: "Tokenisation BLEU difference?",
          a: "1-3 BLEU points — enough to flip a leaderboard ranking." }
      ] },
    { q: "Why is BLEU bad for short outputs?",
      a: "Geometric mean of 1- to 4-gram precisions. Few 4-grams in short text → high variance. BP also tricky at short lengths. Use chrF or BERTScore for short text." },
    { q: "WER > 100% — bug?",
      a: "No, expected with hallucination. WER = (S+D+I)/N; if I > N, WER > 1.0. Use MER for bounded." },
    { q: "Perplexity not comparable across tokenisers — why?",
      a: "Per-token NLL depends on token count. Different tokenisers split differently → different perplexity for same model. Use bits-per-byte." }
  ]
},

audio: {
  title: "Audio",
  summary: "11 metrics — perceptual, SNR, no-reference, separation.",
  metrics: [
    { name: "PESQ", what: "ITU P.862 perceptual quality, MOS-LQO scaled.", when: "Speech quality eval (telecom).", range: "[1, 4.5]", direction: "up",
      scenario: "VoIP codec quality." },
    { name: "STOI", what: "Envelope-feature correlation.", when: "Speech intelligibility.", range: "[0, 1]", direction: "up",
      scenario: "Hearing-aid evaluation." },
    { name: "SNR", what: "10·log10(||s||² / ||noise||²).", when: "Generic with reference.", range: "(-∞, ∞)", direction: "up",
      scenario: "Generic speech quality.",
      pitfall: "Scale-sensitive — use SI-SNR for speech." },
    { name: "SI-SNR", what: "SNR after optimal scalar rescaling.", when: "Speech enhancement.", range: "(-∞, ∞)", direction: "up",
      scenario: "DNS Challenge primary." },
    { name: "SDR", what: "Target / (interference + artifacts).", when: "Source separation.", range: "(-∞, ∞)", direction: "up",
      scenario: "Multi-speaker separation." },
    { name: "SI-SDR", what: "SDR with optimal rescaling.", when: "Source separation benchmarks.", range: "(-∞, ∞)", direction: "up",
      scenario: "WHAM!, LibriMix." },
    { name: "C-SI-SNR", what: "Complex-spectrogram SI-SNR.", when: "Complex-valued speech enhancement.", range: "(-∞, ∞)", direction: "up",
      scenario: "Phase-aware speech enhancement." },
    { name: "PIT", what: "Permutation-invariant assignment loss.", when: "Multi-source separation.", range: "wrapped metric range", direction: "up",
      scenario: "Two-speaker separation training." },
    { name: "DNSMOS", what: "Trained no-reference MOS predictor.", when: "Production DNS / no-reference.", range: "[1, 5]", direction: "up",
      scenario: "DNS Challenge official metric." },
    { name: "NISQA", what: "Non-intrusive MOS + per-aspect.", when: "Telephony quality monitoring.", range: "[1, 5]", direction: "up",
      scenario: "Production telephony QA." },
    { name: "SRMR", what: "Speech-to-reverb modulation energy ratio.", when: "Dereverberation evaluation.", range: "[0, ∞)", direction: "up",
      scenario: "Reverb suppression algorithm eval." }
  ],
  questions: [
    { q: "SNR vs SI-SNR?",
      a: "SI-SNR removes optimal-scaling — measures shape, not amplitude. Standard for speech enhancement training and evaluation." },
    { q: "PIT — what is it?",
      a: "Permutation-invariant training. Multi-source separation: model outputs N waveforms but ordering is arbitrary. PIT picks the optimal assignment to minimise loss." },
    { q: "PESQ deprecated — why?",
      a: "ITU replaced with POLQA (P.863) in 2011 — wideband / super-wideband better. PESQ kept for legacy comparison." }
  ]
},

clustering: {
  title: "Clustering",
  summary: "11 metrics — external (with truth) and internal (geometric).",
  metrics: [
    { name: "RandScore", what: "Pairwise concordance fraction.", when: "Ground-truth comparison.", range: "[0, 1]", direction: "up",
      scenario: "Comparing two partitions of same data.",
      pitfall: "Not chance-corrected — use ARI." },
    { name: "AdjustedRandScore (ARI)", what: "Chance-corrected Rand.", when: "Standard external metric.", range: "[-1, 1]", direction: "up",
      scenario: "New algorithm vs k-means baseline." },
    { name: "MutualInfoScore (MI)", what: "I(X,Y) between partitions.", when: "Information-theoretic comparison.", range: "[0, ∞)", direction: "up",
      scenario: "Information overlap." },
    { name: "NormalizedMI (NMI)", what: "MI / sqrt(H(X)·H(Y)).", when: "Bounded MI.", range: "[0, 1]", direction: "up",
      scenario: "Legacy clustering papers.",
      pitfall: "Not chance-corrected — use AMI." },
    { name: "AdjustedMI (AMI)", what: "Chance-corrected MI.", when: "Default external metric.", range: "[-1, 1]", direction: "up",
      scenario: "Default modern external clustering metric." },
    { name: "FowlkesMallows (FMI)", what: "sqrt(P · R) over pairs.", when: "Pairwise alternative to ARI.", range: "[0, 1]", direction: "up",
      scenario: "Sometimes reported alongside ARI." },
    { name: "Homogeneity", what: "Each cluster pure (one true class).", when: "Diagnose mixed clusters.", range: "[0, 1]", direction: "up",
      scenario: "Cluster-purity diagnostic." },
    { name: "Completeness", what: "Each true class in one cluster.", when: "Diagnose split classes.", range: "[0, 1]", direction: "up",
      scenario: "Class-splitting diagnostic." },
    { name: "V-Measure", what: "Harmonic mean of homogeneity + completeness.", when: "Single-number from H/C.", range: "[0, 1]", direction: "up",
      scenario: "External eval headline." },
    { name: "ClusterAccuracy", what: "Accuracy after Hungarian assignment.", when: "Unsupervised classification.", range: "[0, 1]", direction: "up",
      scenario: "Self-supervised representation eval." },
    { name: "CalinskiHarabaszScore", what: "Between/within dispersion ratio.", when: "k-selection (no truth).", range: "[0, ∞)", direction: "up",
      scenario: "Elbow-rule for choosing k." },
    { name: "DaviesBouldinScore", what: "Mean of within/between dispersion ratios.", when: "Internal compactness.", range: "[0, ∞)", direction: "down",
      scenario: "Cluster-tightness diagnostic." },
    { name: "DunnIndex", what: "Min inter-cluster / max intra-cluster.", when: "Worst-pair compactness.", range: "[0, ∞)", direction: "up",
      scenario: "Sensitive to outliers." }
  ],
  questions: [
    { q: "Why NMI biased? AMI corrects how?",
      a: "Random labelings can score nontrivial NMI. AMI subtracts expected NMI under random labeling and rescales — random scores ≈ 0." },
    { q: "Homogeneity vs completeness vs V-measure?",
      a: "Homogeneity = pure clusters; failure mode is singleton clusters. Completeness = unsplit classes; failure mode is one giant cluster. V is harmonic mean. AMI is the chance-corrected headline." }
  ]
},

nominal: {
  title: "Nominal / categorical",
  summary: "5 metrics — categorical association and inter-rater agreement.",
  metrics: [
    { name: "Cramér's V", what: "sqrt(χ²/(n·min(r-1,c-1))).", when: "Categorical-vs-categorical correlation.", range: "[0, 1]", direction: "up",
      scenario: "EDA categorical correlation matrix.",
      pitfall: "Biased upward at small N — use bias-corrected." },
    { name: "Tschuprow's T", what: "sqrt(χ²/(n·sqrt((r-1)(c-1)))).", when: "Variant of Cramér's V.", range: "[0, 1]", direction: "up",
      scenario: "Same as Cramér's V; different normalisation." },
    { name: "Pearson's contingency C", what: "sqrt(χ²/(χ²+n)).", when: "Legacy alternative.", range: "[0, ~1)", direction: "up",
      scenario: "Legacy contingency analysis.",
      pitfall: "Maximum < 1 and depends on table — comparisons unsafe." },
    { name: "Theil's U", what: "(H(X) − H(X|Y)) / H(X).", when: "Asymmetric / directional.", range: "[0, 1]", direction: "up",
      scenario: "Categorical feature → target predictive power." },
    { name: "Fleiss kappa", what: "Inter-rater agreement (3+ raters).", when: "Multi-annotator agreement.", range: "[-1, 1]", direction: "up",
      scenario: "Annotation campaign QC. κ < 0.4 → fix guidelines." }
  ],
  questions: [
    { q: "Cramér's V vs Theil's U?",
      a: "V symmetric (V(X,Y)=V(Y,X)). Theil's U asymmetric — U(X|Y) measures Y's predictive power for X. Use V for general, U for direction." },
    { q: "What κ values are acceptable for annotation?",
      a: "Landis-Koch: <0.4 poor, 0.4-0.6 moderate, 0.6-0.8 good. Floor for shippable training data: ≥0.6 general, ≥0.7 high-stakes." }
  ]
},

multimodal: {
  title: "Multimodal / video / shape",
  summary: "5 metrics — CLIP, VMAF, Procrustes.",
  metrics: [
    { name: "CLIP Score", what: "Cosine similarity of CLIP image+text embeddings × temperature.", when: "Text-to-image alignment.", range: "[0, 100]", direction: "up",
      scenario: "T2I generation evaluation." },
    { name: "CLIP-IQA", what: "Cosine to 'good photo' / 'bad photo' prompts.", when: "No-reference image quality.", range: "[0, 1]", direction: "up",
      scenario: "User-uploaded content quality." },
    { name: "LVE", what: "Label-and-visual embedding alignment.", when: "Multimodal embedding alignment.", range: "score", direction: "up",
      scenario: "Multimodal model evaluation." },
    { name: "VMAF", what: "Netflix's perceptual video MOS estimator.", when: "Video codec / streaming.", range: "[0, 100]", direction: "up",
      scenario: "Streaming ABR ladder design." },
    { name: "Procrustes Distance", what: "Distance after optimal rotation/translation/scale.", when: "Pose / mesh comparison.", range: "[0, ∞)", direction: "down",
      scenario: "Pose estimation evaluation." }
  ],
  questions: [
    { q: "CLIP score not enough — why?",
      a: "Coarse alignment only. Fails compositional ('red cube on blue sphere'), counting, negation. Combine with FID + compositional benchmarks + human eval." },
    { q: "VMAF vs PSNR for video?",
      a: "VMAF correlates with MOS ~0.9; PSNR ~0.5. Industry standard. Choose VMAF model variant for content type." }
  ]
},

wrappers: {
  title: "Wrappers",
  summary: "10 wrappers — change how a metric is used without re-implementing it.",
  metrics: [
    { name: "BootStrapper", what: "Resample-based mean and std of a metric.", when: "Confidence intervals.", range: "wrapped", direction: "up",
      scenario: "Comparing two models with paired CIs." },
    { name: "ClasswiseWrapper", what: "Per-class metric with separate logging keys.", when: "Per-class dashboard rows.", range: "wrapped", direction: "up",
      scenario: "Multi-class accuracy logged per class." },
    { name: "MetricTracker", what: "Best-of-epoch tracking.", when: "Decoupled from logger 'best so far'.", range: "wrapped", direction: "up",
      scenario: "Best-epoch checkpointing." },
    { name: "MultioutputWrapper", what: "Same metric, multiple outputs.", when: "Multi-target regression.", range: "wrapped", direction: "up",
      scenario: "5-target MAE." },
    { name: "MultitaskWrapper", what: "Different metrics for different heads.", when: "Multi-task model.", range: "wrapped", direction: "up",
      scenario: "Regression + classification heads." },
    { name: "MinMaxMetric", what: "Running min and max alongside current.", when: "Bound monitoring.", range: "wrapped", direction: "up",
      scenario: "Per-epoch loss bounds." },
    { name: "Running", what: "Sliding-window metric.", when: "Online production monitoring.", range: "wrapped", direction: "up",
      scenario: "Rolling 1-hour AUROC." },
    { name: "FeatureShare", what: "Share feature extractor across metrics.", when: "Generative pipelines (FID+KID+IS).", range: "wrapped", direction: "up",
      scenario: "GAN eval — one Inception forward pass." },
    { name: "Transformations", what: "Transform inputs before metric.", when: "Pre-process (log-space R²).", range: "wrapped", direction: "up",
      scenario: "R² in log-space." },
    { name: "Abstract", what: "Base class for custom wrappers.", when: "Composing existing metrics.", range: "wrapped", direction: "up",
      scenario: "Custom composed metric." }
  ],
  questions: [
    { q: "Bootstrap vs multi-seed?",
      a: "Bootstrap = test-set sampling variance. Multi-seed = training-run variance. Paper-grade reporting does both." },
    { q: "compute_groups bites how?",
      a: "Default True dedupes shared state. Custom metrics or randomness can break the heuristic. Set False if uncertain — trades compute for correctness." }
  ]
},

aggregation: {
  title: "Aggregation",
  summary: "8 metrics — DDP-safe stateful reducers.",
  metrics: [
    { name: "SumMetric", what: "Running sum, all_reduce(SUM).", when: "Total counters under DDP.", range: "[-∞, ∞)", direction: "up",
      scenario: "Total tokens processed across ranks." },
    { name: "MeanMetric", what: "Running mean from (sum, count).", when: "Custom average under DDP.", range: "[-∞, ∞)", direction: "up",
      scenario: "Custom per-batch scalar averaged across epoch." },
    { name: "MinMetric", what: "Running min, all_reduce(MIN).", when: "Lower bound across batches.", range: "[-∞, ∞)", direction: "down",
      scenario: "Smallest gradient norm." },
    { name: "MaxMetric", what: "Running max, all_reduce(MAX).", when: "Upper bound across batches.", range: "[-∞, ∞)", direction: "up",
      scenario: "Largest gradient norm." },
    { name: "CatMetric", what: "Concatenate all values across batches.", when: "Need every value (offline analysis).", range: "list", direction: "up",
      scenario: "Collect all predictions under DDP." },
    { name: "RunningSum", what: "Sum over a sliding window.", when: "Recent-only sums.", range: "[-∞, ∞)", direction: "up",
      scenario: "Last-N-step training loss sum." },
    { name: "RunningMean", what: "Mean over a sliding window.", when: "Smoothed loss curve.", range: "[-∞, ∞)", direction: "up",
      scenario: "Last-100-step running training loss." }
  ],
  questions: [
    { q: "Why use these instead of plain Python sums?",
      a: "DDP correctness for free. Single-rank Python sum doesn't aggregate across ranks; SumMetric does via all_reduce." }
  ]
}

};

const SCENARIOS = [
  { name: "1. E-commerce search ranker",
    stack: "NDCG@10 + NDCG@30 + MRR@10 + Hit@1 + per-segment + online A/B",
    why: "NDCG matches user-facing depth; depth diagnostic catches deep-rank-only improvements; online metrics are the ground truth.",
    trap: "Optimising NDCG offline without online checks — judgments are biased toward what the previous ranker showed." },
  { name: "2. Recommendation carousel",
    stack: "Hit@10 + NDCG@10 + MAP@10 + IPS-weighted + diversity (LPIPS) + coverage",
    why: "IPS debias position; diversity guards echo chambers; coverage guards catalog stagnation.",
    trap: "Hit@10 alone — model collapses to popular items, kills long-tail." },
  { name: "3. Spam filter",
    stack: "Precision (high threshold) + RecallAtFixedPrecision(0.99) + AveragePrecision + ECE + per-sender",
    why: "Cost asymmetry: false-positive (real mail in spam) is 10× worse. Constrained recall matches deployment SLA.",
    trap: "Reporting accuracy — 99% accurate at 99% precision still loses 1% real mail = pissed users." },
  { name: "4. Fraud detection",
    stack: "AUPRC + MCC + Recall@(analyst-capacity-threshold) + Precision@K + per-merchant + bootstrap CIs",
    why: "Imbalance kills AUROC. Precision@K matches 'analyst can review 50/day'.",
    trap: "Reporting AUROC 0.99 → 0.995 as 'great improvement' — production lift can be zero, AUPRC reveals." },
  { name: "5. Medical cancer screening",
    stack: "SpecificityAtSensitivity(0.95) + AUROC + ECE + per-subgroup + BinaryFairness + bootstrap",
    why: "Constrained metric matches regulator. Per-subgroup catches scanner / demographic failure.",
    trap: "Raw AUROC alone — regulators reject papers without constraint." },
  { name: "6. ETA prediction (ride-share)",
    stack: "MAE + p99 absolute error + bias + per-segment + per-distance",
    why: "MAE interpretable; p99 captures user frustration outliers; bias matters for trust.",
    trap: "RMSE — over-weights outliers; teams chase one bad trip instead of systematic MAE." },
  { name: "7. Demand forecast (retail)",
    stack: "wMAPE + per-SKU MAE + bias + naive baseline ratio + per-SKU-cluster",
    why: "wMAPE matches P&L. Naive baseline ratio is the only honest 'are we adding value' check.",
    trap: "MAPE alone — tiny-volume SKUs with noisy demand inflate it." },
  { name: "8. Speech recognition",
    stack: "WER + CER + per-domain + per-noise + RTF (latency)",
    why: "Per-condition trumps top-line; production audio is noisier than LibriSpeech-clean.",
    trap: "Reporting LibriSpeech-clean only — production WER often 2-3×." },
  { name: "9. Machine translation",
    stack: "SacreBLEU + chrF + BERTScore + COMET + human pairwise eval",
    why: "BLEU for legacy; chrF for non-English; BERTScore for semantic; human for ship/no-ship.",
    trap: "BLEU 1-point gain shipped without human eval — doesn't always lift human ratings." },
  { name: "10. Summarisation",
    stack: "ROUGE-1/2/L + BERTScore + QA-based factuality + length + human",
    why: "ROUGE for legacy; BERTScore for semantic; QA-based catches hallucination.",
    trap: "ROUGE-only — extractive copy-paste rewarded over abstractive." },
  { name: "11. Question answering (extractive)",
    stack: "SQuAD F1 + EM + ECE + abstention quality",
    why: "Standardised pair; calibration matters because QA triggers downstream actions.",
    trap: "EM-only — F1 captures partial overlap that's often acceptable." },
  { name: "12. Image classification",
    stack: "Acc@1 + Acc@5 + macro F1 + ConfusionMatrix + per-subgroup",
    why: "Top-1 + top-5 + class-balanced view + confusion diagnostic.",
    trap: "Top-line accuracy alone hides per-class failure on rare classes." },
  { name: "13. Object detection",
    stack: "mAP@[.5:.95] + mAP@0.5 + per-area-bucket + per-class AP + latency p99",
    why: "COCO mAP standard; per-bucket diagnoses size regressions; latency for deployment.",
    trap: "Top-line mAP only — 2-point drop hides 'small objects collapsed by 10 points'." },
  { name: "14. Semantic segmentation",
    stack: "MeanIoU + per-class IoU + boundary metric (Hausdorff95)",
    why: "Cityscapes/ADE20K convention. Boundary for safety-critical.",
    trap: "Reporting include_background=True without saying — inflates mIoU 5-10 points." },
  { name: "15. Medical imaging segmentation",
    stack: "Dice per organ + Hausdorff95 (mm) + volume difference + NSD",
    why: "Dice is convention; Hausdorff95 surgical relevance; volume difference catches systematic shrinkage.",
    trap: "Pixel-Hausdorff (not mm) — non-portable across scanners." },
  { name: "16. Generative model (image)",
    stack: "FID@50k + KID + LPIPS pairwise (diversity) + MIFID (memorisation) + human pairwise",
    why: "FID headline; KID unbiased small-N; LPIPS pairwise = diversity; MIFID guards copying.",
    trap: "FID with N=1000 — biased low. Use KID for small-N." },
  { name: "17. Speech enhancement",
    stack: "SI-SNR + SI-SNR-improvement + PESQ-WB + ESTOI + DNSMOS",
    why: "SI-SNR primary; improvement = model contribution; PESQ telecom standard; ESTOI intelligibility; DNSMOS no-reference for prod.",
    trap: "Wrong sample rate — silent garbage from PESQ." },
  { name: "18. Source separation",
    stack: "PIT(SI-SDR) + SI-SDR-improvement + per-source-class",
    why: "PIT handles assignment ambiguity; improvement shows model contribution.",
    trap: "Pure SDR without PIT — random assignment = random gradient." },
  { name: "19. Text-to-image generation",
    stack: "CLIP Score + FID + compositional benchmarks + human",
    why: "CLIP for alignment; FID for fidelity; compositional benchmarks for spatial/counting.",
    trap: "CLIP-only — misses spatial / counting / negation." },
  { name: "20. Video codec / streaming",
    stack: "VMAF + PSNR per-frame (mean+p99) + SSIM + bitrate budget",
    why: "VMAF correlates with MOS; PSNR engineering baseline; SSIM structure check.",
    trap: "PSNR-only — blind to perceptual artefacts." },
  { name: "21. Anomaly detection (time series)",
    stack: "AUPRC + Precision@K + time-to-detect + false-alerts/day",
    why: "Imbalance demands AUPRC; Precision@K = alert budget; TTD = operational quality.",
    trap: "AUROC at 0.1% positive base rate — shows nothing." },
  { name: "22. Drift detection",
    stack: "JS divergence per feature + KS-test + per-segment + alert threshold tuned to FPR",
    why: "JS symmetric and bounded; KS for marginals; per-segment catches partial drift.",
    trap: "Single global alert — daily drift signals on harmless segment." },
  { name: "23. Loan default (compliance)",
    stack: "AUROC + ECE + Brier + BinaryFairness + per-segment AUROC",
    why: "Calibration matters for pricing; fairness ratio is what compliance reads.",
    trap: "Optimising AUROC, shipping with bad calibration → mispriced loans." },
  { name: "24. Self-driving perception",
    stack: "PanopticQuality + mAP detection + MOTA / IDF1 tracking + per-distance + per-condition + latency",
    why: "PQ for unified things+stuff; per-condition catches night/rain failures.",
    trap: "Day-only test set — catastrophic in rain." },
  { name: "25. Code generation",
    stack: "pass@k + edit distance + CodeBLEU + compile rate + human pairwise",
    why: "pass@k = functional correctness, what matters; lexical metrics are correlates.",
    trap: "BLEU-only on code — code can be lexically similar but not run." }
];
